#!/bin/bash

#execute only from within the folder extracted from the win10.tar.gz file!

#Note: No guarantee that this theme will be seen correctly at all screen resolutions available

if [ "$PWD" != "/lib/plymouth/themes/win10" ] ; then
	sudo mkdir /usr/share/plymouth/themes/win10
	clear
	sudo rsync -aq --exclude=install-win10 * /usr/share/plymouth/themes/win10/
	clear
fi
if [ ! -f "/etc/initramfs-tools/conf.d/splash" ]; then
	sudo cp splash /etc/initramfs-tools/conf.d/splash
	clear
	echo
	echo 'Asserted FRAMEBUFFER=y...'
	echo
	echo
fi
PACKAGE=$(dpkg-query -W --showformat='${Status}\n' plymouth-x11 | grep "install ok installed")
if [ "" == "$PACKAGE" ]; then
	echo 'Installing plymouth-x11 to provide for splash testing without restarting the computer.'
	echo
	echo
	sudo apt-get install plymouth-x11
	clear
	echo
	echo 'Installed plymouth-x11 to provide for splash testing without restarting the computer.'
	echo
	echo
fi
sudo update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/win10/win10.plymouth 100
sudo update-alternatives --config default.plymouth  #here, choose the number of the theme you want to use then hit enter
sudo update-initramfs -u
echo
echo
echo Running 10-second test...
sudo plymouthd ; sudo plymouth --show-splash ; for ((I=0; I<10; I++)); do sleep 1 ; sudo plymouth --update=test$I ; done ; sudo plymouth --quit
clear
echo
echo If or when you want to restore the original Plymouth theme, 
echo    execute the script: ./update-plymouth 
echo 
echo If you want to test the theme without re-starting the machine,
echo    execute the script: ./test-plymouth
echo
echo If you want to test the theme after any modifications,
echo    execute the script: ./update-win10
echo
echo Scripts may be executed from the folder where win10.tar.gz was extracted,
echo    OR from /usr/share/plymouth/themes/win10.
echo
echo
read -p "Press ENTER to exit."
exit
